### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by InsanePrawn**
I added extra information regarding the different patch directories and files to the readme. The info is the best of my knowledge gathered from commits, specifically 6accf7917040921c46fded0023464a88bc00377d

### CODE REVIEW

**Comment by hadess** [comment]
Can you add spaces after the comparison signs? Looks good otherwise.

**Comment by InsanePrawn** [comment]
Thanks for the feedback,  using actual words for the comparison sounds much more natural to me and doesn't look as odd to me, hope you agree 😄

**Comment by hadess** [comment]
> Thanks for the feedback, using actual words for the comparison sounds much more natural to me and doesn't look as odd to me, hope you agree :smile:

I'm sorry, but I don't.

**Comment by ribdro** [comment]
In this case, I would generally agree that the symbols are the way to go as
it is a good break between text and numerals.  As a general rule of thumb,
I lean towards verbose and natural language

**Pull request closed without merging**
