### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by cosimoc**
Lots of cleanups wrt. always-on or always-off/commented out code.
Untested yet but builds fine.

### CODE REVIEW

**Comment by hadess** [comment]
The problem with merging this whole request is that at least some of the disabled options might actually have a use, and they would need to be handled on a case-by-case basis. Maybe @lwfinger can help.

**Comment by cosimoc** [comment]
@hadess I see what you mean. Not all the options I have removed are from autoconf.h though... If @lwfinger knows more that'd be fantastic.

**Comment by lwfinger** [comment]
I have not looked at the actual commits, but if they do what their subjects say, then most are OK. The only configuration parameters that you might want to keep are CONFIG_80211D and CONFIG_IEEE80211W. Most APs do not implement 802.11d, but I think you should enable it particularly as this driver does not use the standard regulatory database in Linux. Enabling 802.11w is more of a problem, but some users may need to have management frames encrypted. For that reason, I would leave the option in, at least for now. Bastien also asked about WAPI. How many Chinese will be using this driver?  I doubt that there will be many, and you can probably remove this code as well. Testing it would be impossible.

**Comment by hadess** [comment]
@cosimoc can you rebase without removing the options Larry mentioned?

@lwfinger thanks a lot for looking into this. I don't know how many Chinese folks would use this driver, but this card looks pretty common in tablets usually only sold in China (at least the Onda Cosimo and I both have, and a Teclast that another person has). If it's unsupportable from our side, I'm fine with removing it...

**Comment by hadess** [comment]
I've pushed all the fixes with the 2 mentioned commits removed. Thanks Cosimo!

**Pull request closed without merging**
